version: "3.4"

services:
  yii2:
    build: ./nginx
    container_name: yii2
    volumes:
      - ../api:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/startup.sh:/docker-entrypoint.d/startup.sh
    ports:
      - "80:80"
    restart: always