version: "3.9"

services:
  yii2:
    build: ./nginx
    container_name: yii2
    volumes:
      - ../:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/startup.sh:/docker-entrypoint.d/startup.sh
    ports:
      - "80:80"
      - "8080:8080"
    restart: always
    networks:
      - dev

  yii2-mariadb:
    image: mariadb
    container_name: yii2-mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
    networks:
      - dev
networks:
  dev:
   driver: bridge